import "./globals.css";
import { Actor } from "next/font/google";

const actor = Actor({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={actor.className}>{children}</body>
    </html>
  );
}
